package android.zero.studio.compose.preview.kotlin

import org.jetbrains.kotlin.cli.common.messages.CompilerMessageSeverity

/**
 * Represents a diagnostic report generated by the Kotlin compiler during static analysis.
 * This data class captures the location, message, and severity of a compiler-detected issue.
 * 
 * 工作流程:
 * 1. 编译器在分析源码时生成诊断信息。
 * 2. 诊断信息被映射为此 [AnalysisReport] 实例。
 * 3. 包含文件路径、在文档中的起始与结束偏移量、具体消息以及严重等级（错误、警告等）。
 *
 * @property path The absolute or relative path to the file where the diagnostic was generated. Defaults to null.
 * @property startOffset The zero-based character offset where the reported issue starts.
 * @property endOffset The zero-based character offset where the reported issue ends.
 * @property message The detailed description of the diagnostic provided by the compiler.
 * @property severity The severity level of the diagnostic (e.g., ERROR, WARNING, INFO).
 * 
 * @author android_zero
 */
data class AnalysisReport(
    val path: String? = null,
    val startOffset: Int,
    val endOffset: Int,
    val message: String,
    val severity: CompilerMessageSeverity
) {
    /**
     * Note: As this is a data class, the following methods are automatically generated by the compiler
     * based on the properties defined in the primary constructor, ensuring a 1:1 logical match
     * with the decompiled bytecode:
     * - component1() -> path
     * - component2() -> startOffset
     * - component3() -> endOffset
     * - component4() -> message
     * - component5() -> severity
     * - copy(...)
     * - equals()
     * - hashCode()
     * - toString()
     */
}